server:
  port: 9092

spring:
  application:
    name: apigateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true    

resilience4j:
  circuitbreaker:
    instances:
      fetchfirstapp: 
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 6
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        
      
 
