server:
  port: 8081
  servlet:
    context-path: /app
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/legato_db?autoreconnect = true
    username: root
  jpa:
    hibernate:
      ddl-auto: create
user:name = praveen kumar
